# Generated by Django 3.1.6 on 2022-08-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220809_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.BooleanField(default=True, verbose_name='Лайк'),
        ),
    ]
