# Generated by Django 3.1.6 on 2022-08-12 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220812_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user', verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user', verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='shares',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Poster', to='blog.user', verbose_name='Відправник'),
        ),
        migrations.AlterField(
            model_name='shares',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Geter', to='blog.user', verbose_name='Отримувач'),
        ),
    ]
