# Generated by Django 3.1.6 on 2022-08-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('blog', '0014_auto_20220812_2201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
