# Generated by Django 3.1.6 on 2022-08-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Категорія')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Опис')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Фото')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час останньої зміни')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Категорії')),
            ],
            options={
                'verbose_name': 'Головоломка',
                'verbose_name_plural': 'Головоломки',
                'ordering': ['id'],
            },
        ),
    ]
