# Generated by Django 3.1.6 on 2022-08-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='likes',
            new_name='like',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
