# Generated by Django 3.1.6 on 2022-08-12 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.puzzle', verbose_name='Стаття')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Poster', to=settings.AUTH_USER_MODEL, verbose_name='Відправник1')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Geter', to=settings.AUTH_USER_MODEL, verbose_name='Відправник2')),
            ],
        ),
    ]
